### PR TITLE
chore(test): update from template-formula

### PR DESCRIPTION
**Pull request by jle35**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [x] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [x] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Match TEMPLATE-FORMULA CI process.
Add all lint test and semantic release.

Many minor syntax change for lint tests pass with success

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@jle35 Nice work, thanks for providing this.  I'll check this through when I get a chance and get back to you with the necessary feedback.

**Comment by myii** [comment]
@jle35 This is an excellent conversion for the first attempt.  There are a number of little issues that come up upon review, so I'll be sharing those with you soon.  One of the interesting findings it that it actually works with _all_ of the platforms available.  I've demonstrated here, with the newest pre-salted images available:

* https://travis-ci.com/github/myii/consul-formula/builds/154842610

**Review by myii — CHANGES_REQUESTED** [review]
@jle35 First thing is to remove the second commit made by the `semantic-release-bot`.  That will be done when `semantic-release` is run after this PR is merged.

After that, this commit here shows the diff, to get this synchronised with all of the other 60+ semantic-release formulas in the org:

* https://github.com/myii/consul-formula/commit/228cb2ef11c7431d55063078288b8904275ad28e

Please don't make _all_ of the changes manually at your end.  Once we've finalised the small changes on your side, I'll add my commit to this PR to finish it.

The small changes to make to the first commit (amend):

* Remove all of the unnecessary files (that are shown as deleted in the commit diff):
  - AUTHORS.md 
  - CHANGELOG.md
  - docs/AUTHORS.rst
  - docs/CHANGELOG.rst
  - docs/CONTRIBUTING_DOCS.rst
  - docs/TOFS_pattern.rst
  - docs/_static/css/custom.css
  - docs/conf.py
  - docs/index.rst
* Feel free to make the other minor fixes, such as:
  - .gitignore
  - .rubocop.yml
  - FORMULA 
  - pillar.example
  - release-rules.js

Other than that, please ensure you've set `Allow edits from maintainers.`, so that I can add my commit to this after your changes.

Also note, it's nearly always a good idea to use a [feature branch](https://guides.github.com/introduction/flow/) for PRs, rather than your `master` branch.

**Comment by jle35** [comment]
Hello @myii, 
Thanks for review.
I make some changes you requests, I hope it's good.
I am not sure what to do with with FORMULA file, so I don't touch him.
Allow edit from maintainers is already enable.

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
Merged, thanks for this excellent contribution @jle35!

**Pull request merged**
