### PR TITLE
Create data dir based on pillar value

### PR DESCRIPTION
**Pull request by askainet**
- create data dir based on pillar value
- remove unneeded runtime dir

### CODE REVIEW

**Review by vutny — APPROVED** [review]
Awesome!
That hard-coded directory `/usr/local/share/consul` seems to be never actually used or configured in the `config.json`.

I hope this would be merged. Thanks!

**Review by vutny — COMMENTED** [review]
Hi @babilen , please take a look at this one? I think it is good to be brought in. Thanks.

**Comment by javierbertoli** [comment]
Thanks!

**Comment by vutny** [comment]
Kudos for the heads-up, @javierbertoli !

**Pull request merged**
