### PR TITLE
Use symlinks to versioned binaries to handle version updates

### PR DESCRIPTION
**Pull request by bahadir**

### CODE REVIEW

**Comment by puneetk** [comment]
nice repo, please dont self merge. Also if you could change it around a lil to be similar to the template-formula.

**Comment by bahadir** [comment]
Alright, sorry about that.

**Comment by puneetk** [comment]
not a problem at all, its not doc'ed :) , as in the no self merge thing is somethign we enforce by ourselves. We havent put that down anywhere

**Comment by bahadir** [comment]
OK, I'll split install and service formulas and also fix state names.

**Pull request merged**
